POST https://digitomy.instructure.com/api/lti/courses/4/line_items/2/scores?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF0Zm9ybVVybCI6Imh0dHBzOi8vY2FudmFzLmluc3RydWN0dXJlLmNvbSIsImNsaWVudElkIjoiMjE5MzAwMDAwMDAwMDAwMDA0IiwiZGVwbG95bWVudElkIjoiNjpjYjNjYmRiODAxNWIyNDkxZjczODUzYjA1YmVlZmMxNjJjODUwY2JlIiwicGxhdGZvcm1Db2RlIjoibHRpYUhSMGNITTZMeTlqWVc1MllYTXVhVzV6ZEhKMVkzUjFjbVV1WTI5dE1qRTVNekF3TURBd01EQXdNREF3TURBME5qcGpZak5qWW1SaU9EQXhOV0l5TkRreFpqY3pPRFV6WWpBMVltVmxabU14TmpKak9EVXdZMkpsIiwiY29udGV4dElkIjoiaHR0cHMlM0ElMkYlMkZjYW52YXMuaW5zdHJ1Y3R1cmUuY29tMjE5MzAwMDAwMDAwMDAwMDA0NiUzQWNiM2NiZGI4MDE1YjI0OTFmNzM4NTNiMDViZWVmYzE2MmM4NTBjYmU3YmI4ZDVjNjMyYjViNTM0ZjQ3OGM1ZmE3MDk0MTcwZDRiODEzNTcxXzMzMDNjMDEyLTdjYTUtNGRmMC05NDNkLTRlZTQwNDNlYWUyYiIsInVzZXIiOiJlNWM3YTdiNi1kYjU5LTRjMjItODYzMS05MWIxYTFjOTk0YTkiLCJzIjoiMTk1YmRiNWQzOTk3MjE3YWE5MDkzODA0MWMzYzAzOTEzYTNkMTFiY2U2NGY0NzlmZGMiLCJpYXQiOjE2NjYyOTY0NjB9.MTeqJ8zwwZng5X4d7z6kh0GaalFZjauojHyQlUyaR9A